{% set name = "polars-hash" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/polars_hash-{{ version }}.tar.gz
    sha256: 126419548711867f1cc63b2c2682cb224d262ecce48461ed11dd1f3b32e16cbf
  - url: https://raw.githubusercontent.com/ion-elgreco/polars-hash/main/LICENSE
    sha256: 017feb4ae87126410f1d9beb6af4c9df3c25a0051d87db66da6f26c509f5348d

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - make
  host:
    - python
    - maturin >=1.0,<2.0
    - pip
  run:
    - python
    - polars >=1.5.0

test:
  imports:
    - polars_hash
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ion-elgreco/polars-hash
  summary: Stable non-cryptographic and cryptographic hashing functions for Polars
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - moritzwilksch
